name: Android CI

on:
    push:
      branches: [ main, develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./DeliBuddy
      NAVER_MAP_APIKEY_ID: ${{ secrets.NAVER_MAP_APIKEY_ID }}
      NAVER_MAP_APIKEY_SECRET: ${{ secrets.NAVER_MAP_APIKEY_SECRET }}
      KAKAO_LOCAL_API_KEY: ${{ secrets.KAKAO_LOCAL_API_KEY }}
      KAKAO_LOGIN_API_KEY: ${{ secrets.KAKAO_LOGIN_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Access NAVER_MAP_APIKEY_ID
      run: echo NAVER_MAP_APIKEY_ID=\"$NAVER_MAP_APIKEY_ID\" > ./local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: Access NAVER_MAP_APIKEY_SECRET
      run: echo NAVER_MAP_APIKEY_SECRET=\"$NAVER_MAP_APIKEY_SECRET\" >> ./local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: Access KAKAO_LOCAL_API_KEY
      run: echo KAKAO_LOCAL_API_KEY=\"$KAKAO_LOCAL_API_KEY\" >> ./local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: Access KAKAO_LOGIN_API_KEY
      run: echo KAKAO_LOGIN_API_KEY=\"$KAKAO_LOGIN_API_KEY\" >> ./local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ env.working-directory }}
